-- Supabase setup SQL for 01_chatbot_basic.
-- This script does not use Supabase Auth. It creates the tables expected by
-- the FastAPI/SQLAlchemy app and inserts a small set of dummy data.

create table if not exists public.users (
  id integer generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(255) unique,
  created_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  title varchar(200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id integer generated by default as identity primary key,
  conversation_id integer not null references public.conversations(id) on delete cascade,
  role varchar(20) not null check (role in ('USER', 'ASSISTANT')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists ix_users_id on public.users(id);
create index if not exists ix_users_email on public.users(email);
create index if not exists ix_conversations_id on public.conversations(id);
create index if not exists ix_conversations_user_id on public.conversations(user_id);
create index if not exists ix_messages_id on public.messages(id);
create index if not exists ix_messages_conversation_id on public.messages(conversation_id);
create index if not exists ix_messages_role on public.messages(role);
create index if not exists ix_messages_created_at on public.messages(created_at);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_conversations_updated_at on public.conversations;

create trigger set_conversations_updated_at
before update on public.conversations
for each row
execute function public.set_updated_at();

insert into public.users (id, name, email)
values
  (1, 'Demo User', 'demo@example.com'),
  (2, 'Student User', 'student@example.com')
on conflict (id) do update
set
  name = excluded.name,
  email = excluded.email;

insert into public.conversations (id, user_id, title)
values
  (1, 1, 'PostgreSQL 질문'),
  (2, 2, '학습 상담')
on conflict (id) do update
set
  user_id = excluded.user_id,
  title = excluded.title,
  updated_at = now();

insert into public.messages (id, conversation_id, role, content)
values
  (1, 1, 'USER', 'PostgreSQL로 대화 기록을 저장하는 이유를 알려줘'),
  (2, 1, 'ASSISTANT', 'PostgreSQL을 사용하면 대화 기록을 안정적으로 저장하고, 사용자별 대화 이력을 효율적으로 조회할 수 있습니다.'),
  (3, 2, 'USER', '오늘 공부 계획을 세우고 싶어요'),
  (4, 2, 'ASSISTANT', '좋습니다. 오늘 학습할 과목, 사용할 수 있는 시간, 가장 어려운 단원을 기준으로 계획을 세워볼 수 있습니다.')
on conflict (id) do update
set
  conversation_id = excluded.conversation_id,
  role = excluded.role,
  content = excluded.content;

select setval(pg_get_serial_sequence('public.users', 'id'), coalesce((select max(id) from public.users), 1));
select setval(pg_get_serial_sequence('public.conversations', 'id'), coalesce((select max(id) from public.conversations), 1));
select setval(pg_get_serial_sequence('public.messages', 'id'), coalesce((select max(id) from public.messages), 1));
